package com.jackson.screeninsight;

import android.app.Activity;import android.app.AlertDialog;import android.app.TimePickerDialog;import android.content.Intent;import android.graphics.Color;import android.os.Build;import android.os.Bundle;import android.provider.Settings;import android.view.Gravity;import android.widget.Button;import android.widget.LinearLayout;import android.widget.NumberPicker;import android.widget.ScrollView;import android.widget.Switch;import android.widget.TextView;import java.util.Calendar;import java.util.Locale;

public final class MainActivity extends Activity {
    private LinearLayout box;
    @Override public void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},7);ReportScheduler.schedule(this);load();}
    @Override protected void onResume(){super.onResume();if(box!=null)load();}
    private void load(){box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(36,65,36,40);box.setBackgroundColor(Color.rgb(16,24,32));ScrollView sc=new ScrollView(this);sc.addView(box);setContentView(sc);box.addView(text("Screen Insight",30,Color.WHITE));
        Button access=new Button(this);access.setText("开启使用情况访问权限");access.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS)));box.addView(access);
        box.addView(text("正在读取本机数据…",16,Color.LTGRAY));new Thread(()->{UsageAnalyzer.Report r=UsageAnalyzer.analyze(this);runOnUiThread(()->render(r));}).start();}
    private void render(UsageAnalyzer.Report r){while(box.getChildCount()>2)box.removeViewAt(2);double change=r.previous==0?0:(r.total-r.previous)*100.0/r.previous;
        box.addView(text("最近7天  "+UsageAnalyzer.duration(r.total),25,Color.rgb(72,202,228)));box.addView(text(r.previous==0?"上周数据不足":String.format(Locale.getDefault(),"相比上周 %+.0f%%",change),17,change>10?Color.rgb(255,120,120):Color.LTGRAY));
        box.addView(text("每天使用趋势",19,Color.WHITE));String[] days={"一","二","三","四","五","六","日"};box.addView(new UsageChart(this,r.days,days,Color.rgb(72,202,228)),new LinearLayout.LayoutParams(-1,310));
        int peak=0,low=0;for(int i=1;i<24;i++){if(r.hours[i]>r.hours[peak])peak=i;if(r.hours[i]<r.hours[low])low=i;}box.addView(text("使用高峰："+String.format("%02d:00–%02d:00",peak,(peak+1)%24)+"   最低："+String.format("%02d:00–%02d:00",low,(low+1)%24),17,Color.LTGRAY));
        long[] blocks=new long[8];String[] bl=new String[8];for(int i=0;i<8;i++){for(int h=i*3;h<i*3+3;h++)blocks[i]+=r.hours[h];bl[i]=String.format("%02d",i*3);}box.addView(new UsageChart(this,blocks,bl,Color.rgb(255,183,77)),new LinearLayout.LayoutParams(-1,310));
        box.addView(text("工作/学习："+UsageAnalyzer.duration(r.productive)+"   娱乐："+UsageAnalyzer.duration(r.leisure),18,Color.WHITE));box.addView(text("首次使用："+UsageAnalyzer.time(r.first)+"\n最后使用："+UsageAnalyzer.time(r.last)+"\n深夜使用："+UsageAnalyzer.duration(r.late),16,Color.LTGRAY));
        box.addView(text("本周建议",20,Color.rgb(128,222,234)));box.addView(text(r.advice,17,Color.WHITE));box.addView(text("使用最多的 App",20,Color.WHITE));int n=Math.min(8,r.apps.size());for(int i=0;i<n;i++){UsageAnalyzer.AppRow a=r.apps.get(i);box.addView(text((i+1)+". "+a.name+"  "+UsageAnalyzer.duration(a.ms)+"  · "+category(a.category),16,Color.LTGRAY));}
        Button cats=new Button(this);cats.setText("编辑 App 分类");cats.setOnClickListener(v->startActivity(new Intent(this,CategoryActivity.class)));box.addView(cats);
        Button report=new Button(this);report.setText(reportText());report.setOnClickListener(v->showReportSettings());box.addView(report);
        Switch notify=new Switch(this);notify.setText("每周报告通知");notify.setTextColor(Color.WHITE);notify.setChecked(getSharedPreferences(ReportScheduler.PREFS,0).getBoolean(ReportScheduler.ENABLED,true));notify.setOnCheckedChangeListener((v,on)->{getSharedPreferences(ReportScheduler.PREFS,0).edit().putBoolean(ReportScheduler.ENABLED,on).apply();if(on)ReportScheduler.schedule(this);else ReportScheduler.cancel(this);});box.addView(notify);
        Button refresh=new Button(this);refresh.setText("刷新数据");refresh.setOnClickListener(v->load());box.addView(refresh);}
    private String category(int c){return c==1?"工作/学习":c==-1?"娱乐":"未分类";}
    private String reportText(){int d=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.DAY,Calendar.SUNDAY),h=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.HOUR,19),m=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.MINUTE,0);String[] names={"","周日","周一","周二","周三","周四","周五","周六"};return String.format(Locale.getDefault(),"周报时间：%s %02d:%02d",names[d],h,m);}
    private void showReportSettings(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);NumberPicker day=new NumberPicker(this);day.setMinValue(1);day.setMaxValue(7);day.setDisplayedValues(new String[]{"周日","周一","周二","周三","周四","周五","周六"});day.setValue(getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.DAY,1));Button time=new Button(this);int oldH=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.HOUR,19),oldM=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.MINUTE,0);final int[] hm={oldH,oldM};time.setText(String.format("%02d:%02d",oldH,oldM));time.setOnClickListener(v->new TimePickerDialog(this,(p,h,m)->{hm[0]=h;hm[1]=m;time.setText(String.format("%02d:%02d",h,m));},hm[0],hm[1],true).show());row.addView(day);row.addView(time);new AlertDialog.Builder(this).setTitle("设置每周报告").setView(row).setNegativeButton("取消",null).setPositiveButton("保存",(d,w)->{getSharedPreferences(ReportScheduler.PREFS,0).edit().putInt(ReportScheduler.DAY,day.getValue()).putInt(ReportScheduler.HOUR,hm[0]).putInt(ReportScheduler.MINUTE,hm[1]).apply();ReportScheduler.cancel(this);ReportScheduler.schedule(this);load();}).show();}
    private TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,14,0,14);return t;}
}
