package com.jackson.screeninsight;

import android.app.Activity;import android.app.AlertDialog;import android.app.AppOpsManager;import android.app.NotificationManager;import android.app.TimePickerDialog;import android.content.Intent;import android.content.pm.ApplicationInfo;import android.graphics.Color;import android.os.Build;import android.os.Bundle;import android.provider.Settings;import android.view.Gravity;import android.widget.Button;import android.widget.HorizontalScrollView;import android.widget.ImageView;import android.widget.LinearLayout;import android.widget.NumberPicker;import android.widget.ScrollView;import android.widget.Switch;import android.widget.TextView;import java.text.SimpleDateFormat;import java.util.Calendar;import java.util.Date;import java.util.Locale;

public final class MainActivity extends Activity {
    private LinearLayout box;
    @Override public void onCreate(Bundle b){super.onCreate(b);ReportScheduler.schedule(this);ReportScheduler.scheduleDaily(this);load();}
    @Override protected void onResume(){super.onResume();if(box!=null)load();}
    private void load(){box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(36,35,36,40);box.setBackgroundColor(Color.rgb(16,24,32));ScrollView sc=new ScrollView(this);sc.addView(box);setContentView(sc);ImageView brand=new ImageView(this);brand.setImageResource(com.jackson.screeninsight.R.drawable.screen_insight_brand);brand.setScaleType(ImageView.ScaleType.CENTER_CROP);box.addView(brand,new LinearLayout.LayoutParams(-1,300));box.addView(text("Screen Insight",30,Color.WHITE));
        boolean usageOk=hasUsageAccess(),noticeOk=getSystemService(NotificationManager.class).areNotificationsEnabled();box.addView(text("版本 1.4  ·  五类智能统计",15,Color.GRAY));box.addView(text("只申请必要权限",19,Color.WHITE));Button access=new Button(this);access.setText(usageOk?"✓ 屏幕时间读取已授权":"必需：授权读取屏幕时间");access.setOnClickListener(v->openUsageSettings());box.addView(access);Button notice=new Button(this);notice.setText(noticeOk?"✓ 报告通知已授权":"可选：开启日报和周报通知");notice.setOnClickListener(v->requestNoticePermission());box.addView(notice);box.addView(text("不会申请：通讯录、短信、电话、相册、文件、位置、相机或麦克风。",14,Color.GRAY));
        if(!usageOk){box.addView(text("尚未获得使用情况访问权限，因此目前无法读取屏幕时间。\n\n点击上方按钮 → 在系统列表找到 Screen Insight → 打开“允许使用情况访问” → 返回本 App。\n\n此权限只提供 App 名称、使用时长和使用时间，不会读取聊天内容、密码或屏幕画面。",18,Color.rgb(255,190,120)));return;}
        box.addView(text("正在读取本机数据…",16,Color.LTGRAY));new Thread(()->{UsageAnalyzer.Report r=UsageAnalyzer.analyze(this);runOnUiThread(()->render(r));}).start();}
    private void render(UsageAnalyzer.Report r){while(box.getChildCount()>2)box.removeViewAt(2);double change=r.previous==0?0:(r.total-r.previous)*100.0/r.previous;
        int today=(Calendar.getInstance().get(Calendar.DAY_OF_WEEK)+5)%7,goal=getSharedPreferences("goals",0).getInt("daily_minutes",240);box.addView(text("本周  "+UsageAnalyzer.duration(r.total),25,Color.rgb(72,202,228)));box.addView(text(r.previous==0?"上周数据不足":String.format(Locale.getDefault(),"相比上周 %+.0f%%",change),17,change>10?Color.rgb(255,120,120):Color.LTGRAY));box.addView(text("今日 "+UsageAnalyzer.duration(r.days[today])+" / 目标 "+UsageAnalyzer.duration(goal*60_000L),18,r.days[today]>goal*60_000L?Color.rgb(255,120,120):Color.rgb(120,220,170)));
        box.addView(text("本周每天（左右滑动，触摸柱子看数值）",19,Color.WHITE));String[] days={"一","二","三","四","五","六","日"};UsageChart weekly=new UsageChart(this,r.days,days,Color.rgb(72,202,228));weekly.setMinimumWidth(1050);HorizontalScrollView whs=new HorizontalScrollView(this);whs.addView(weekly,new HorizontalScrollView.LayoutParams(1050,310));box.addView(whs);
        box.addView(text("每日明细",19,Color.WHITE));for(int i=0;i<7;i++)box.addView(text("周"+days[i]+"  "+UsageAnalyzer.duration(r.days[i])+"  首次 "+clock(r.dayFirst[i])+"  最后 "+clock(r.dayLast[i])+"  深夜 "+UsageAnalyzer.duration(r.dayLate[i]),15,i>=5?Color.rgb(255,203,107):Color.LTGRAY));
        int peak=0,low=0;for(int i=1;i<24;i++){if(r.hours[i]>r.hours[peak])peak=i;if(r.hours[i]<r.hours[low])low=i;}box.addView(text("使用高峰："+String.format("%02d:00–%02d:00",peak,(peak+1)%24)+"   最低："+String.format("%02d:00–%02d:00",low,(low+1)%24),17,Color.LTGRAY));
        long[] blocks=new long[8];String[] bl=new String[8];for(int i=0;i<8;i++){for(int h=i*3;h<i*3+3;h++)blocks[i]+=r.hours[h];bl[i]=String.format("%02d",i*3);}box.addView(new UsageChart(this,blocks,bl,Color.rgb(255,183,77)),new LinearLayout.LayoutParams(-1,310));
        box.addView(text("最近30天（左右滑动）",19,Color.WHITE));String[] ml=new String[30];Calendar mc=Calendar.getInstance();mc.add(Calendar.DAY_OF_YEAR,-29);SimpleDateFormat md=new SimpleDateFormat("M/d",Locale.getDefault());for(int i=0;i<30;i++){ml[i]=md.format(mc.getTime());mc.add(Calendar.DAY_OF_YEAR,1);}UsageChart monthly=new UsageChart(this,r.monthDays,ml,Color.rgb(137,207,240));monthly.setMinimumWidth(2100);HorizontalScrollView hs=new HorizontalScrollView(this);hs.addView(monthly,new HorizontalScrollView.LayoutParams(2100,310));box.addView(hs);
        box.addView(text("五类时间分布",20,Color.WHITE));String[] cn={"股票投资","工作学习","娱乐","微信社交","事务处理"};for(int i=0;i<5;i++)box.addView(text(cn[i]+"："+UsageAnalyzer.duration(r.categories[i]),17,i==2?Color.rgb(255,190,130):Color.LTGRAY));box.addView(text("本周深夜使用："+UsageAnalyzer.duration(r.late),16,Color.LTGRAY));
        box.addView(text("本周建议",20,Color.rgb(128,222,234)));box.addView(text(r.advice,17,Color.WHITE));box.addView(text("使用最多的 App",20,Color.WHITE));int n=Math.min(8,r.apps.size());for(int i=0;i<n;i++){UsageAnalyzer.AppRow a=r.apps.get(i);box.addView(text((i+1)+". "+a.name+"  "+UsageAnalyzer.duration(a.ms)+"  · "+category(a.category),16,Color.LTGRAY));}
        Button cats=new Button(this);cats.setText("编辑 App 分类");cats.setOnClickListener(v->startActivity(new Intent(this,CategoryActivity.class)));box.addView(cats);
        Button goalButton=new Button(this);goalButton.setText("设置每日屏幕目标");goalButton.setOnClickListener(v->showGoal());box.addView(goalButton);
        Button report=new Button(this);report.setText(reportText());report.setOnClickListener(v->showReportSettings());box.addView(report);
        Switch notify=new Switch(this);notify.setText("每周报告通知");notify.setTextColor(Color.WHITE);notify.setChecked(getSharedPreferences(ReportScheduler.PREFS,0).getBoolean(ReportScheduler.ENABLED,true));notify.setOnCheckedChangeListener((v,on)->{getSharedPreferences(ReportScheduler.PREFS,0).edit().putBoolean(ReportScheduler.ENABLED,on).apply();if(on)ReportScheduler.schedule(this);else ReportScheduler.cancel(this);});box.addView(notify);
        Button dailyTime=new Button(this);dailyTime.setText(dailyText());dailyTime.setOnClickListener(v->showDailyTime());box.addView(dailyTime);Switch daily=new Switch(this);daily.setText("每日简报通知");daily.setTextColor(Color.WHITE);daily.setChecked(getSharedPreferences(ReportScheduler.PREFS,0).getBoolean(ReportScheduler.DAILY_ENABLED,true));daily.setOnCheckedChangeListener((v,on)->{getSharedPreferences(ReportScheduler.PREFS,0).edit().putBoolean(ReportScheduler.DAILY_ENABLED,on).apply();if(on)ReportScheduler.scheduleDaily(this);else ReportScheduler.cancelDaily(this);});box.addView(daily);
        Button refresh=new Button(this);refresh.setText("刷新数据");refresh.setOnClickListener(v->load());box.addView(refresh);}
    private String category(int c){return UsageAnalyzer.categoryName(c);}
    private boolean hasUsageAccess(){AppOpsManager a=(AppOpsManager)getSystemService(APP_OPS_SERVICE);int mode=a.checkOpNoThrow(AppOpsManager.OPSTR_GET_USAGE_STATS,android.os.Process.myUid(),getPackageName());return mode==AppOpsManager.MODE_ALLOWED;}
    private void openUsageSettings(){try{startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS,android.net.Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS));}}
    private void requestNoticePermission(){if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},7);else startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()));}
    private void showGoal(){NumberPicker p=new NumberPicker(this);p.setMinValue(1);p.setMaxValue(12);p.setValue(getSharedPreferences("goals",0).getInt("daily_minutes",240)/60);p.setFormatter(v->v+"小时");new AlertDialog.Builder(this).setTitle("每日屏幕时间目标").setView(p).setNegativeButton("取消",null).setPositiveButton("保存",(d,w)->{getSharedPreferences("goals",0).edit().putInt("daily_minutes",p.getValue()*60).apply();load();}).show();}
    private String clock(long ms){return ms==0?"--:--":new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(ms));}
    private String dailyText(){int h=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.DAILY_HOUR,9),m=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.DAILY_MINUTE,0);return String.format(Locale.getDefault(),"每日简报时间：%02d:%02d",h,m);}
    private void showDailyTime(){int h=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.DAILY_HOUR,9),m=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.DAILY_MINUTE,0);new TimePickerDialog(this,(p,hh,mm)->{getSharedPreferences(ReportScheduler.PREFS,0).edit().putInt(ReportScheduler.DAILY_HOUR,hh).putInt(ReportScheduler.DAILY_MINUTE,mm).apply();ReportScheduler.cancelDaily(this);ReportScheduler.scheduleDaily(this);load();},h,m,true).show();}
    private String reportText(){int d=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.DAY,Calendar.SUNDAY),h=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.HOUR,19),m=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.MINUTE,0);String[] names={"","周日","周一","周二","周三","周四","周五","周六"};return String.format(Locale.getDefault(),"周报时间：%s %02d:%02d",names[d],h,m);}
    private void showReportSettings(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);NumberPicker day=new NumberPicker(this);day.setMinValue(1);day.setMaxValue(7);day.setDisplayedValues(new String[]{"周日","周一","周二","周三","周四","周五","周六"});day.setValue(getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.DAY,1));Button time=new Button(this);int oldH=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.HOUR,19),oldM=getSharedPreferences(ReportScheduler.PREFS,0).getInt(ReportScheduler.MINUTE,0);final int[] hm={oldH,oldM};time.setText(String.format("%02d:%02d",oldH,oldM));time.setOnClickListener(v->new TimePickerDialog(this,(p,h,m)->{hm[0]=h;hm[1]=m;time.setText(String.format("%02d:%02d",h,m));},hm[0],hm[1],true).show());row.addView(day);row.addView(time);new AlertDialog.Builder(this).setTitle("设置每周报告").setView(row).setNegativeButton("取消",null).setPositiveButton("保存",(d,w)->{getSharedPreferences(ReportScheduler.PREFS,0).edit().putInt(ReportScheduler.DAY,day.getValue()).putInt(ReportScheduler.HOUR,hm[0]).putInt(ReportScheduler.MINUTE,hm[1]).apply();ReportScheduler.cancel(this);ReportScheduler.schedule(this);load();}).show();}
    private TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,14,0,14);return t;}
}
