package com.jackson.screeninsight;

import android.app.Notification;import android.app.NotificationChannel;import android.app.NotificationManager;import android.app.PendingIntent;import android.content.BroadcastReceiver;import android.content.Context;import android.content.Intent;

public final class ReportReceiver extends BroadcastReceiver {
    @Override public void onReceive(Context c,Intent i){UsageAnalyzer.Report r=UsageAnalyzer.analyze(c);boolean daily="DAILY".equals(i.getAction());NotificationManager nm=c.getSystemService(NotificationManager.class);String id=daily?"daily_screen_report":"weekly_screen_report";nm.createNotificationChannel(new NotificationChannel(id,daily?"每日屏幕简报":"每周屏幕时间报告",NotificationManager.IMPORTANCE_DEFAULT));Intent detail=new Intent(c,ReportActivity.class).putExtra("daily",daily);PendingIntent open=PendingIntent.getActivity(c,daily?93:94,detail,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);String title=daily?"昨日简报":"本周复盘";String body=daily?dailyText(r):weeklyText(r);Notification n=new Notification.Builder(c,id).setSmallIcon(android.R.drawable.ic_menu_recent_history).setContentTitle(title).setContentText(body).setStyle(new Notification.BigTextStyle().bigText(body)).setContentIntent(open).setAutoCancel(true).build();nm.notify(daily?301:300,n);if(daily)ReportScheduler.scheduleDaily(c);else ReportScheduler.schedule(c);}
    private String dailyText(UsageAnalyzer.Report r){java.util.Calendar c=java.util.Calendar.getInstance();c.add(java.util.Calendar.DAY_OF_YEAR,-1);int y=(c.get(java.util.Calendar.DAY_OF_WEEK)+5)%7;int before=(y+6)%7;long diff=r.days[y]-r.days[before];String trend=r.days[before]==0?"正在建立日常基线":diff<0?"比前一天少看了"+UsageAnalyzer.duration(-diff):"比前一天多看了"+UsageAnalyzer.duration(diff);String late=r.dayLate[y]>30*60_000L?"；昨晚深夜使用"+UsageAnalyzer.duration(r.dayLate[y])+"，今天试着提前一点放下手机":"；昨晚深夜使用不多，继续保持";return trend+late+"。";}
    private String weeklyText(UsageAnalyzer.Report r){double change=r.previous==0?0:(r.total-r.previous)*100.0/r.previous;String trend=r.previous==0?"基线建立中":change>0?"总量 +"+Math.round(change)+"%":"总量 "+Math.round(change)+"%";String focus=r.late>3*60*60_000L?"深夜使用 "+UsageAnalyzer.duration(r.late):r.leisure>r.productive?"娱乐时间偏高":"节奏总体稳定";return "• "+trend+"  • "+focus+"\n点击查看完整报告";}
}
