package com.jackson.screeninsight;

import android.app.usage.UsageEvents;import android.app.usage.UsageStats;import android.app.usage.UsageStatsManager;import android.content.Context;import android.content.pm.ApplicationInfo;import android.content.pm.PackageManager;
import java.text.SimpleDateFormat;import java.util.ArrayList;import java.util.Calendar;import java.util.Collections;import java.util.Comparator;import java.util.HashMap;import java.util.List;import java.util.Locale;import java.util.Map;

final class UsageAnalyzer {
    static final int ENTERTAINMENT=-1,UNCATEGORIZED=0,WORK_STUDY=1,INVESTING=2,SOCIAL=3,ADMIN=4;
    static final class AppRow {String pkg,name;long ms;int category;}
    static final class Report {long total,previous,late,previousLate;long[] days=new long[7],hours=new long[24],dayFirst=new long[7],dayLast=new long[7],dayLate=new long[7],monthDays=new long[30],categories=new long[5];long productive,leisure,lateProductive,lateLeisure;String topLateApp="";List<AppRow> apps=new ArrayList<>();String advice="";}
    static Report analyze(Context c){
        Report r=new Report();Calendar end=Calendar.getInstance();long now=end.getTimeInMillis();Calendar start=(Calendar)end.clone();start.set(Calendar.HOUR_OF_DAY,0);start.set(Calendar.MINUTE,0);start.set(Calendar.SECOND,0);start.set(Calendar.MILLISECOND,0);start.add(Calendar.DAY_OF_YEAR,-((start.get(Calendar.DAY_OF_WEEK)+5)%7));Calendar prev=(Calendar)start.clone();prev.add(Calendar.DAY_OF_YEAR,-7);
        r.apps=apps(c,start.getTimeInMillis(),now);for(AppRow a:r.apps){r.total+=a.ms;if(a.category==WORK_STUDY||a.category==INVESTING||a.category==ADMIN)r.productive+=a.ms;if(a.category==ENTERTAINMENT)r.leisure+=a.ms;int ci=categoryIndex(a.category);if(ci>=0)r.categories[ci]+=a.ms;}
        for(AppRow a:apps(c,prev.getTimeInMillis(),start.getTimeInMillis()))r.previous+=a.ms;
        Calendar month=(Calendar)end.clone();month.add(Calendar.DAY_OF_YEAR,-30);sessions(c,month.getTimeInMillis(),now,r);Report old=new Report();sessions(c,prev.getTimeInMillis(),start.getTimeInMillis(),old);r.previousLate=old.late;r.advice=KnowledgeBase.advice(r);return r;
    }
    static List<AppRow> apps(Context c,long from,long to){
        UsageStatsManager us=(UsageStatsManager)c.getSystemService(Context.USAGE_STATS_SERVICE);Map<String,UsageStats> raw=us.queryAndAggregateUsageStats(from,to);List<AppRow> out=new ArrayList<>();PackageManager pm=c.getPackageManager();
        for(UsageStats u:raw.values()){if(u.getTotalTimeInForeground()<60_000||u.getPackageName().equals(c.getPackageName()))continue;AppRow a=new AppRow();a.pkg=u.getPackageName();a.ms=u.getTotalTimeInForeground();a.name=a.pkg;try{ApplicationInfo i=pm.getApplicationInfo(a.pkg,0);a.name=pm.getApplicationLabel(i).toString();}catch(Exception ignored){}a.category=category(c,a.pkg);out.add(a);}
        Collections.sort(out,(a,b)->Long.compare(b.ms,a.ms));return out;
    }
    private static void sessions(Context c,long from,long to,Report r){
        UsageStatsManager us=(UsageStatsManager)c.getSystemService(Context.USAGE_STATS_SERVICE);UsageEvents es=us.queryEvents(from,to);UsageEvents.Event e=new UsageEvents.Event();Map<String,Long> active=new HashMap<>(),lateByApp=new HashMap<>();Calendar cal=Calendar.getInstance();long statsFrom=from;if(to-from>8L*24*60*60_000L){Calendar wk=Calendar.getInstance();wk.set(Calendar.HOUR_OF_DAY,0);wk.set(Calendar.MINUTE,0);wk.set(Calendar.SECOND,0);wk.set(Calendar.MILLISECOND,0);wk.add(Calendar.DAY_OF_YEAR,-((wk.get(Calendar.DAY_OF_WEEK)+5)%7));statsFrom=wk.getTimeInMillis();}
        while(es.hasNextEvent()){es.getNextEvent(e);int type=e.getEventType();String pkg=e.getPackageName();if(type==UsageEvents.Event.ACTIVITY_RESUMED)active.put(pkg,e.getTimeStamp());else if(type==UsageEvents.Event.ACTIVITY_PAUSED){Long s=active.remove(pkg);if(s==null||e.getTimeStamp()<=s)continue;long d=Math.min(e.getTimeStamp()-s,4*60*60_000L);cal.setTimeInMillis(s);int ago=(int)((System.currentTimeMillis()-s)/(24*60*60_000L));if(ago>=0&&ago<30)r.monthDays[29-ago]+=d;int ix=(cal.get(Calendar.DAY_OF_WEEK)+5)%7;if(s>=statsFrom&&s<=to){r.days[ix]+=d;r.hours[cal.get(Calendar.HOUR_OF_DAY)]+=d;if(r.dayFirst[ix]==0||s<r.dayFirst[ix])r.dayFirst[ix]=s;if(e.getTimeStamp()>r.dayLast[ix])r.dayLast[ix]=e.getTimeStamp();if(cal.get(Calendar.HOUR_OF_DAY)>=23||cal.get(Calendar.HOUR_OF_DAY)<6){r.late+=d;r.dayLate[ix]+=d;lateByApp.put(pkg,lateByApp.getOrDefault(pkg,0L)+d);int cat=category(c,pkg);if(cat==WORK_STUDY||cat==INVESTING||cat==ADMIN)r.lateProductive+=d;if(cat==ENTERTAINMENT)r.lateLeisure+=d;}}}}
        long best=0;for(Map.Entry<String,Long>x:lateByApp.entrySet())if(x.getValue()>best){best=x.getValue();r.topLateApp=x.getKey();}if(!r.topLateApp.isEmpty())try{ApplicationInfo i=c.getPackageManager().getApplicationInfo(r.topLateApp,0);r.topLateApp=c.getPackageManager().getApplicationLabel(i).toString();}catch(Exception ignored){}
    }
    static int category(Context c,String pkg){int saved=c.getSharedPreferences("categories",0).getInt(pkg,99);if(saved!=99)return saved;String p=pkg.toLowerCase(Locale.ROOT);if(p.contains("tradingview")||p.contains("invest")||p.contains("broker")||p.contains("stocks")||p.contains("finance")||p.contains("yahoo"))return INVESTING;if(p.contains("chatgpt")||p.contains("openai")||p.contains("office")||p.contains("docs")||p.contains("notion"))return WORK_STUDY;if(p.contains("wechat")||p.contains("tencent.mm")||p.contains("whatsapp")||p.contains("telegram")||p.contains("messenger"))return SOCIAL;if(p.contains("calendar")||p.contains("bank")||p.contains("email")||p.contains("gmail")||p.contains("maps")||p.contains("xero"))return ADMIN;if(p.contains("tiktok")||p.contains("instagram")||p.contains("facebook")||p.contains("youtube")||p.contains("reddit")||p.contains("xiaohongshu")||p.contains("xingin")||p.contains("game"))return ENTERTAINMENT;return UNCATEGORIZED;}
    static int categoryIndex(int c){return c==INVESTING?0:c==WORK_STUDY?1:c==ENTERTAINMENT?2:c==SOCIAL?3:c==ADMIN?4:-1;}
    static String categoryName(int c){return c==INVESTING?"股票投资":c==WORK_STUDY?"工作学习":c==ENTERTAINMENT?"娱乐":c==SOCIAL?"微信社交":c==ADMIN?"事务处理":"未分类";}
    static void setCategory(Context c,String pkg,int v){c.getSharedPreferences("categories",0).edit().putInt(pkg,v).apply();}
    static String duration(long ms){long m=ms/60_000;return String.format(Locale.getDefault(),"%d小时%02d分",m/60,m%60);}
    static String time(long ms){return ms==0?"暂无":new SimpleDateFormat("EEE HH:mm",Locale.getDefault()).format(ms);}
}
